include:
    - template: Auto-DevOps.gitlab-ci.yml

stages:
    - arc_json
    - quality_report_generator
    - quality_report
    - generate_metadata
    - arc-summary

arc-summary:
    stage: arc-summary
    image: docker:24.0.7
    services:
      - name: docker:24.0.7-dind
        alias: docker
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
    script:
      - echo "Create ARC summary in README.md as job artifact"
      - docker run --rm -v "$CI_PROJECT_DIR:/arc" ghcr.io/nfdi4plants/arc-summary:main summary -d /arc
    artifacts:
      paths:
        - README.md
      expire_in: 1 week
    only:
      - main
